# Generated by Django 3.0.5 on 2020-05-04 15:16

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Appointment address')),
                ('description', models.TextField(verbose_name='Description')),
                ('time_slot', models.CharField(max_length=255, verbose_name='Timeslot')),
                ('waiver', models.FileField(upload_to='waivers/%Y/%m/')),
                ('status', models.CharField(choices=[('waiver-emailed', 'Pending: waiver emailed to client (waiting on client)'), ('waiver-signed', 'Pending: waiver signed and returned (awaiting scheduling)'), ('confirmed', 'Confirmed: client scheduled')], max_length=255, verbose_name='Status')),
                ('language', models.CharField(choices=[('korean-no-interpreter', 'Mono-lingual Korean: need interpreter'), ('korean-with-interpreter', 'Mono-lingual Korean: bringing own interpreter'), ('english', 'English: no interpreter needed')], max_length=255, verbose_name='Language')),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinics.Clinic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
