# Generated by Django 3.0.5 on 2020-05-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attorney',
            field=models.CharField(blank=True, max_length=255, verbose_name='Attorney'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('waiver-emailed', 'Pending: waiver emailed to client (waiting on client)'), ('waiver-signed', 'Pending: waiver signed and returned (awaiting scheduling)'), ('confirmed', 'Confirmed: client scheduled')], max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('07:00:00', '7:00 AM'), ('07:30:00', '7:30 AM'), ('08:00:00', '8:00 AM'), ('08:30:00', '8:30 AM'), ('09:00:00', '9:00 AM'), ('09:30:00', '9:30 AM'), ('10:00:00', '10:00 AM'), ('10:30:00', '10:30 AM'), ('11:00:00', '11:00 AM'), ('11:30:00', '11:30 AM'), ('12:00:00', 'Noon'), ('12:30:00', '12:30 PM'), ('13:00:00', '1:00 PM'), ('13:30:00', '1:30 PM'), ('14:00:00', '2:00 PM'), ('14:30:00', '2:30 PM'), ('15:00:00', '3:00 PM'), ('15:30:00', '3:30 PM'), ('16:00:00', '4:00 PM'), ('16:30:00', '4:30 PM'), ('17:00:00', '5:00 PM'), ('17:30:00', '5:30 PM'), ('18:00:00', '6:00 PM'), ('18:30:00', '6:30 PM'), ('19:00:00', '7:00 PM'), ('19:30:00', '7:30 PM'), ('20:00:00', '8:00 PM'), ('20:30:00', '8:30 PM'), ('21:30:00', '9:00 PM'), ('21:00:00', '9:30 PM')], max_length=255, verbose_name='Timeslot'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='waiver',
            field=models.FileField(blank=True, upload_to='waivers/%Y/%m/'),
        ),
    ]
