# Generated by Django 3.0.5 on 2020-05-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20200504_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='language',
            field=models.CharField(choices=[('korean-no-interpreter', 'Korean: Need interpreter'), ('korean-with-interpreter', 'Korean: Bringing interpreter'), ('english', 'English: no interpreter needed')], max_length=255, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('waiver-emailed', 'Step 1: Pending waiver return'), ('waiver-signed', 'Step 2: Pending scheduling'), ('confirmed', 'Step 3: Client scheduled'), ('confirmed-with-attorney', 'Step 4: Client AND attorney scheduled')], default='waiver-emailed', max_length=255, verbose_name='Status'),
        ),
    ]
