# Generated by Django 3.0.5 on 2020-05-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20200504_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.CharField(default='No address', max_length=255, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
