# Generated by Django 3.0.5 on 2020-05-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Time slot'),
        ),
    ]
