# Generated by Django 3.0.5 on 2020-05-11 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20200510_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='attorney',
        ),
    ]
