# Generated by Django 3.0.5 on 2020-05-11 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0001_initial'),
        ('appointments', '0009_remove_appointment_attorney'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attorney',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='attorneys.Attorney'),
        ),
    ]
