# Generated by Django 3.0.5 on 2020-05-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_attorney'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['admin_order']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='admin_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
