# Generated by Django 3.0.5 on 2020-05-12 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0001_initial'),
        ('appointments', '0011_auto_20200512_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='attorney',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='attorneys.Attorney'),
        ),
    ]
