# Generated by Django 3.0.5 on 2020-05-08 15:38

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Organization')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Organization link')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('website', models.URLField(max_length=255, verbose_name='Website')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
