# Generated by Django 3.0.5 on 2020-05-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='abbreviation',
            field=models.CharField(default='KCS', max_length=10, verbose_name='Organization abbreviation'),
            preserve_default=False,
        ),
    ]
