# Generated by Django 3.0.5 on 2020-05-15 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attorney',
            options={'ordering': ('name',)},
        ),
    ]
