# Generated by Django 3.0.5 on 2020-05-04 17:23

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('organization', models.CharField(choices=[('kcs', 'Korean Community Services (KCS)'), ('kaf', 'Korean American Federation (KAF)')], max_length=50, verbose_name='Organization')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.DateField(verbose_name='Date'), unique=True, verbose_name='Clinic URL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
