# Generated by Django 3.0.5 on 2020-05-04 15:16

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('organization', models.CharField(max_length=50, verbose_name='Organization')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.DateField(verbose_name='Date'), unique=True, verbose_name='Clinic URL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
