# Generated by Django 3.0.5 on 2020-05-09 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_abbreviation'),
        ('clinics', '0004_auto_20200508_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.AlterModelOptions(
            name='clinic',
            options={'default_permissions': ('add',)},
        ),
        migrations.AddField(
            model_name='clinic',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='organizations.Organization'),
        ),
    ]
