# Generated by Django 3.0.5 on 2020-05-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_auto_20200509_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='group',
            field=models.CharField(default='KAF', max_length=255, verbose_name='Group'),
            preserve_default=False,
        ),
    ]
