# Generated by Django 3.0.5 on 2020-05-08 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('clinics', '0005_clinic_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='organizations.Organization'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
