# Generated by Django 3.0.5 on 2020-05-09 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_clinic_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={},
        ),
    ]
