# Generated by Django 3.0.5 on 2020-05-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_auto_20200509_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='user',
            field=models.CharField(default='KCS', max_length=255, verbose_name='Group'),
            preserve_default=False,
        ),
    ]
