# Generated by Django 3.0.5 on 2020-05-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_clinic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='user',
            field=models.CharField(max_length=255, verbose_name='User'),
        ),
    ]
