# Generated by Django 3.0.5 on 2020-05-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_auto_20200509_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='group',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='user',
        ),
    ]
