# Generated by Django 3.0.5 on 2020-05-09 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0010_auto_20200509_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
