# Generated by Django 3.0.5 on 2020-05-09 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0011_clinic_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='clinic',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
