# Generated by Django 3.0.5 on 2020-05-09 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0012_auto_20200509_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='modified_by',
        ),
    ]
