# Generated by Django 3.0.5 on 2020-05-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_auto_20200509_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='time_slots',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Time slots'),
        ),
    ]
