# Generated by Django 3.0.5 on 2020-05-10 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0015_clinic_time_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='end_time',
            field=models.TimeField(choices=[(datetime.datetime(1, 1, 1, 7, 0), '7:00 AM'), (datetime.datetime(1, 1, 1, 8, 0), '8:00 AM'), (datetime.datetime(1, 1, 1, 8, 30), '8:30 AM'), (datetime.datetime(1, 1, 1, 9, 0), '9:00 AM'), (datetime.datetime(1, 1, 1, 9, 30), '9:30 AM'), (datetime.datetime(1, 1, 1, 10, 0), '10:00 AM'), (datetime.datetime(1, 1, 1, 10, 30), '10:30 AM'), (datetime.datetime(1, 1, 1, 11, 0), '11:00 AM'), (datetime.datetime(1, 1, 1, 11, 30), '11:30 AM'), (datetime.datetime(1, 1, 1, 12, 0), '12:00 PM'), (datetime.datetime(1, 1, 1, 12, 30), '12:30 PM'), (datetime.datetime(1, 1, 1, 13, 0), '1:00 PM'), (datetime.datetime(1, 1, 1, 13, 30), '1:30 PM'), (datetime.datetime(1, 1, 1, 14, 0), '2:00 PM'), (datetime.datetime(1, 1, 1, 14, 30), '2:30 PM'), (datetime.datetime(1, 1, 1, 15, 0), '3:00 PM'), (datetime.datetime(1, 1, 1, 15, 30), '3:30 PM'), (datetime.datetime(1, 1, 1, 16, 0), '4:00 PM'), (datetime.datetime(1, 1, 1, 16, 30), '4:30 PM'), (datetime.datetime(1, 1, 1, 17, 0), '5:00 PM'), (datetime.datetime(1, 1, 1, 17, 30), '5:30 PM'), (datetime.datetime(1, 1, 1, 18, 0), '6:00 PM'), (datetime.datetime(1, 1, 1, 18, 30), '6:30 PM'), (datetime.datetime(1, 1, 1, 19, 0), '7:00 PM'), (datetime.datetime(1, 1, 1, 19, 30), '7:30 PM'), (datetime.datetime(1, 1, 1, 20, 0), '8:00 PM'), (datetime.datetime(1, 1, 1, 20, 30), '8:30 PM')], verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='start_time',
            field=models.TimeField(choices=[(datetime.datetime(1, 1, 1, 7, 0), '7:00 AM'), (datetime.datetime(1, 1, 1, 8, 0), '8:00 AM'), (datetime.datetime(1, 1, 1, 8, 30), '8:30 AM'), (datetime.datetime(1, 1, 1, 9, 0), '9:00 AM'), (datetime.datetime(1, 1, 1, 9, 30), '9:30 AM'), (datetime.datetime(1, 1, 1, 10, 0), '10:00 AM'), (datetime.datetime(1, 1, 1, 10, 30), '10:30 AM'), (datetime.datetime(1, 1, 1, 11, 0), '11:00 AM'), (datetime.datetime(1, 1, 1, 11, 30), '11:30 AM'), (datetime.datetime(1, 1, 1, 12, 0), '12:00 PM'), (datetime.datetime(1, 1, 1, 12, 30), '12:30 PM'), (datetime.datetime(1, 1, 1, 13, 0), '1:00 PM'), (datetime.datetime(1, 1, 1, 13, 30), '1:30 PM'), (datetime.datetime(1, 1, 1, 14, 0), '2:00 PM'), (datetime.datetime(1, 1, 1, 14, 30), '2:30 PM'), (datetime.datetime(1, 1, 1, 15, 0), '3:00 PM'), (datetime.datetime(1, 1, 1, 15, 30), '3:30 PM'), (datetime.datetime(1, 1, 1, 16, 0), '4:00 PM'), (datetime.datetime(1, 1, 1, 16, 30), '4:30 PM'), (datetime.datetime(1, 1, 1, 17, 0), '5:00 PM'), (datetime.datetime(1, 1, 1, 17, 30), '5:30 PM'), (datetime.datetime(1, 1, 1, 18, 0), '6:00 PM'), (datetime.datetime(1, 1, 1, 18, 30), '6:30 PM'), (datetime.datetime(1, 1, 1, 19, 0), '7:00 PM'), (datetime.datetime(1, 1, 1, 19, 30), '7:30 PM'), (datetime.datetime(1, 1, 1, 20, 0), '8:00 PM'), (datetime.datetime(1, 1, 1, 20, 30), '8:30 PM')], verbose_name='Start time'),
        ),
    ]
